### ISSUE TITLE
Rotate packages

### ISSUE THREAD

**Issue by jmgk77** [rogerdahl/striprouter-cpp#4]
Hi,

It would be nice if we could rotate packages, either automatically or manually (right click).

Let's say:
```
# Packages
R 0,0 1,0

# Components
R1 R 3,3

```

This put resistor R pin 1 at 3,3 and pin 2 at 4,3.

Rotating it would put it at 3,3-3,4; 3,3-3,2 or 3,3-2,3

This would improve routing, i believe

**Comment by rogerdahl** [comment]
It's a great idea and should be easy to add. Did you compile from scratch or use one of the binaries?

**Comment by rogerdahl** [comment]
Thinking about this a bit more, for packages that have a row of pins, only 180 degree rotations would make sense.

Since the copper strips are vertically oriented, connections to components can only be done from above or below, not from the sides.

**Comment by jmgk77** [comment]
i used the precompiled linux package
