### ISSUE TITLE
Internal connections

### ISSUE THREAD

**Issue by fharni** [rogerdahl/striprouter-cpp#9]
Some components have pins internaly connected, like the GND pin. I wish to make internal connected pins configurable. At the moment when I configure that two pins of the same component are connected, the algorythm will make an separatire jumper wire.

**Comment by rogerdahl** [comment]
Good point. That would definitely be useful, but it's unfortunately not implemented. I'm rewriting this application in Rust and have added a ticket for it over there. https://github.com/rogerdahl/striprouter/issues/1

In the meantime, I think you'll have to give the two GND pins different names, like GND1 and GND2, and specify directly which ones you want to use for the connections.
